package com.shop.Dao;

import java.util.List;

import com.shop.DaoObject.UserAddressDao;

public interface UserAddressDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int insert(UserAddressDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int insertSelective(UserAddressDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    UserAddressDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserAddressDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int updateByPrimaryKey(UserAddressDao record);

	List<UserAddressDao> selectByUserId(Integer id);
}