package com.shop.Dao;

import java.util.List;

import com.shop.DaoObject.UserAllreadyBuyDao;

public interface UserAllreadyBuyDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int insert(UserAllreadyBuyDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int insertSelective(UserAllreadyBuyDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    UserAllreadyBuyDao selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int updateByPrimaryKeySelective(UserAllreadyBuyDao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_allreadybuy
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    int updateByPrimaryKey(UserAllreadyBuyDao record);

	List<UserAllreadyBuyDao> selectByUserId(Integer id);
}