package com.shop.DaoObject;

public class UserAllreadyBuyDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_allreadybuy.id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_allreadybuy.AllreadyBuyItems
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    private String allreadybuyitems;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_allreadybuy.user_id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_allreadybuy.id
     *
     * @return the value of user_allreadybuy.id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_allreadybuy.id
     *
     * @param id the value for user_allreadybuy.id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_allreadybuy.AllreadyBuyItems
     *
     * @return the value of user_allreadybuy.AllreadyBuyItems
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public String getAllreadybuyitems() {
        return allreadybuyitems;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_allreadybuy.AllreadyBuyItems
     *
     * @param allreadybuyitems the value for user_allreadybuy.AllreadyBuyItems
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public void setAllreadybuyitems(String allreadybuyitems) {
        this.allreadybuyitems = allreadybuyitems == null ? null : allreadybuyitems.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_allreadybuy.user_id
     *
     * @return the value of user_allreadybuy.user_id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_allreadybuy.user_id
     *
     * @param userId the value for user_allreadybuy.user_id
     *
     * @mbg.generated Fri Feb 15 11:54:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}