package com.shop.DaoObject;

public class UserAddressDao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.Man
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private String man;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.Post
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private Integer post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.ManTele
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    private String mantele;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.id
     *
     * @return the value of user_address.id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.id
     *
     * @param id the value for user_address.id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address
     *
     * @return the value of user_address.address
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address
     *
     * @param address the value for user_address.address
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.Man
     *
     * @return the value of user_address.Man
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public String getMan() {
        return man;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.Man
     *
     * @param man the value for user_address.Man
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setMan(String man) {
        this.man = man == null ? null : man.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.Post
     *
     * @return the value of user_address.Post
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public Integer getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.Post
     *
     * @param post the value for user_address.Post
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setPost(Integer post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.ManTele
     *
     * @return the value of user_address.ManTele
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public String getMantele() {
        return mantele;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.ManTele
     *
     * @param mantele the value for user_address.ManTele
     *
     * @mbg.generated Wed Feb 20 09:27:07 CST 2019
     */
    public void setMantele(String mantele) {
        this.mantele = mantele == null ? null : mantele.trim();
    }
}